### ISSUE TITLE
Can you releases  EXE

### ISSUE THREAD

**Issue by xiatiantiantian** [Drexel2k/VidUp#1]
I want to test   Video Uploader ，  TKS

**Comment by Drexel2k** [comment]
Hello,

you find the releases here: https://1drv.ms/u/s!AlNGd4g1Vh9rmHAvaCyZ5nvtOkDF?e=5vhucP

And here you find information about the tool (in German language): https://letsplayforum.de/thread/178125-drexel-s-vidup-ein-templatebasierter-youtube-uploader/

1.1.1.0 is current release. It has 2 known small bugs:
-If the filename contains non ASCII chars the upload will fail.
-If the day is the last of the month publish at doesn't work...

1.2.0.0.Alpha is a debug build with no funtional changes, but I did a lot of architectural changes in the code to ease maintenance in the future.
