### ISSUE TITLE
Crash after Start

### ISSUE THREAD

**Issue by computergott** [Drexel2k/VidUp#4]
Version 1.3.0.2

![enter image description here](https://i.imgur.com/oW5EeCD.png)

System.Windows.Markup.XamlParseException: Durch den Aufruf des Konstruktors für Typ "Drexel.VidUp.UI.ViewModels.MainWindowViewModel", der den angegebenen Bindungseinschränkungen entspricht, wurde eine Ausnahme ausgelöst. ---> Newtonsoft.Json.JsonSerializationException: Unexpected token while deserializing object: PropertyName. Path '[0].guid', line 3, position 11.
bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
bei Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
bei Drexel.VidUp.Json.JsonDeserialization.deserializeTemplateList() in D:\Daten\Matthias\Dokumente\Visual Studio 2019\VidUp\VidUp.Json\JsonDeserialization.cs:Zeile 108.
bei Drexel.VidUp.Json.JsonDeserialization.Deserialize() in D:\Daten\Matthias\Dokumente\Visual Studio 2019\VidUp\VidUp.Json\JsonDeserialization.cs:Zeile 45.
bei Drexel.VidUp.UI.ViewModels.MainWindowViewModel.deserialize() in D:\Daten\Matthias\Dokumente\Visual Studio 2019\VidUp\VidUp.UI\ViewModels\MainWindowViewModel.cs:Zeile 147.
bei Drexel.VidUp.UI.ViewModels.MainWindowViewModel.initialize(UploadList& uploadList, TemplateList& templateList, PlaylistList& playlistList) in D:\Daten\Matthias\Dokumente\Visual Studio 2019\VidUp\VidUp.UI\ViewModels\MainWindowViewModel.cs:Zeile 70.
bei Drexel.VidUp.UI.ViewModels.MainWindowViewModel..ctor() in D:\Daten\Matthias\Dokumente\Visual Studio 2019\VidUp\VidUp.UI\ViewModels\MainWindowViewModel.cs:Zeile 53.
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
bei System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
bei System.Windows.Application.DoStartup()
bei System.Windows.Application.<.ctor>b__1_0(Object unused)
bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
bei System.Windows.Threading.DispatcherOperation.Invoke()
bei System.Windows.Threading.Dispatcher.ProcessQueue()
bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
bei System.Windows.Application.RunDispatcher(Object ignore)
bei System.Windows.Application.RunInternal(Window window)
bei Drexel.VidUp.UI.App.Main()

**Comment by Drexel2k** [comment]
It was announced in the patch notes that the json files structure changed a little bit and needed manual adjustment.
