### ISSUE TITLE
''This app is blocked''

### ISSUE THREAD

**Issue by Redkits02** [Drexel2k/VidUp#6]
Whenever trying to upload, can't bypass the ''This app is blocked'' screen
![app blocked](https://user-images.githubusercontent.com/94436403/141940049-a27b5f94-fc1d-4aee-97f2-971a9e49c61f.png)

enabling ''account access'' or ''less secure apps'' does not help

**Comment by Drexel2k** [comment]
I have this problem also with another user, I don't know exactly where the problem is. I try to get the app verified by google, maybe that helps, but need to set up a heompage and privacy statement etc. for this. It will take some time.
But I see that also other apps have this issue...

**Comment by Drexel2k** [comment]
Hey!
I think I found the reason for the issue:
Without verification by google, the app is limited to 100 users, I wasn't aware of this anymore:
https://imgur.com/35scXls
And the 100 users limit seems to be reached now.

I will try to get the app verified soon, I hope I get it prepared this or next week, but the verification process on google's site will take 4-6 weeks. I will keep you informed.

**Comment by Drexel2k** [comment]
The app is in verification now, it may tale some weeks, cross your fingers. ;)

**Comment by Drexel2k** [comment]
App is now verified by Google, so new users are possible again and the problem should not occure anymore.
