### ISSUE TITLE
Can i make it to publish public a video from folder every 6 hours ?

### ISSUE THREAD

**Issue by dori921** [Drexel2k/VidUp#8]
I have 600 videos in a folder and what to publish 1 every 6 hours.How can i do it ?
Thanks in advance

**Comment by Drexel2k** [comment]
You can't do every 6 hours currently, as there are only 3 time slots in the publish at schedule, so you can only do every 24/3 = 8 hours.

Maybe in future versions I can extend the time slots to 5 or make them totally flexible that you can add as many as you want, but I can't promise, when this will be.

**Comment by Drexel2k** [comment]
A workaround would be:

Make 2 template and put half of the files in one folder and half in another. Make the template for the first folder publish at 1am and 7am and the template for the other folder 1pm and 7 pm... e.g.

**Comment by dori921** [comment]
Going to test it right now.Thanks for your response

**Comment by dori921** [comment]
When I start upload it upload and schedule the first video then it stops(reached the qoute) does it resume by itself ?

**Comment by Drexel2k** [comment]
No it won't restart by itself. I had to throttle the uploads to one per minute, as comment and short spammers started using my app. Unfortunately on the YouTube backend I can only throttle on a per minute basis and not on a per day basis. I would also prefer to set max 10 uploads per day than 1 upload per minute, but I can't do that...
